# Generated by Django 4.2 on 2023-05-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_user_info_groups_user_info_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='user_permissions',
        ),
    ]
