# Generated by Django 4.2 on 2023-05-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_remove_user_info_id_user_info_task1_user_info_task2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
