# Generated by Django 4.2 on 2023-05-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_user_info_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='task5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_info',
            name='task6',
            field=models.IntegerField(default=0),
        ),
    ]
